### PR TITLE
Add the Accumulator interface to StreamingQuantile

### PR DESCRIPTION
**Pull request by jwills**
Matt-- you're absolutely right, thanks for pointing that out. Added here.

### CODE REVIEW

**Comment by matthayes** [comment]
nice!

**Comment by dvryaboy** [comment]
sure would.

I've been meaning to write a harness for easily testing algebraics and accumulatives.. they both have weird implementation quirks, it'd be nice if idf authors could just extend an AgebraicTestCase or something. More motivation....

**Comment by jwills** [comment]
Okay, I figured out the problem. Here was the unit test that passed:

register $JAR_PATH

define Quantile datafu.pig.stats.StreamingQuantile('5');

data_in = LOAD 'input' as (val:int);

/_describe data_in;_/

data_out = GROUP data_in ALL;

/_describe data_out;_/

data_out = FOREACH data_out GENERATE Quantile(data_in.val) as quantiles;
data_out = FOREACH data_out GENERATE FLATTEN(quantiles) as quantiles;

/_describe data_out;_/

STORE data_out into 'output';

...I'm thinking that the useless FLATTEN call after the UDF was called caused Pig to not use the Accumulator interface. When I removed that line, the test failed.

**Comment by matthayes** [comment]
Is there a way to exercise the call method for a UDF which implements Accumulator?

**Pull request merged**
